language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
before_install:
- sudo apt-get install openssl
- openssl aes-256-cbc -K $encrypted_0a740d02c24d_key -iv $encrypted_0a740d02c24d_iv -in travis_CI_id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "Waydrow"
- git config --global user.email waydrow@163.com
- git clone -b gh-pages git@github.com:Waydrow/My-Blog.git .deploy_git
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save
- npm install hexo-generator-sitemap --save
script:
# - hexo clean
- hexo generate
- hexo deploy
