language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_5266d8e6dee5_key -iv $encrypted_5266d8e6dee5_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "Waydrow"
- git config --global user.email waydrow@163.com
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save
- npm install hexo-generator-sitemap --save
script:
- hexo generate
- hexo deploy